---
title: "R Notebook"
output: html_notebook
---

# 1)POSE
```{r}
setwd("C:/Users/nicol/Documents/School Work/year 4/EEB313/pH data")
require(data.table)

# POSE - 2017 September 
POSE_2017.09.02<- fread("POSE.pH.2017.09.csv")
POSE_2017.09.02<- POSE_2017.09.02%>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2017.09.02<- POSE_2017.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2018 March 

POSE_2018.03.01<- fread("POSE.pH.2018.03.01.csv")
POSE_2018.03.01<- POSE_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.03.01<- POSE_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2018.03.02<- fread("POSE.pH.2018.03.02.csv")
POSE_2018.03.02<- POSE_2018.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.03.02<- POSE_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2018 June

POSE_2018.06.01<- fread("POSE.pH.2018.06.01.csv")
POSE_2018.06.01<- POSE_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.06.01<- POSE_2018.06.01 %>% 
 group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2018.06.02<- fread("POSE.pH.2018.06.02.csv")
POSE_2018.06.02<- POSE_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.06.02<- POSE_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2018 September

POSE_2018.09.01<- fread("POSE.pH.2018.09.01.csv")
POSE_2018.09.01<- POSE_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.09.01<- POSE_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2018.09.02<- fread("POSE.pH.2018.09.02.csv")
POSE_2018.09.02<- POSE_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2018.09.02<- POSE_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2019 March 

POSE_2019.03.01<- fread("POSE.pH.2019.03.01.csv")
POSE_2019.03.01<- POSE_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.03.01<- POSE_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2019.03.02<- fread("POSE.pH.2019.03.02.csv")
POSE_2019.03.02<- POSE_2019.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.03.02<- POSE_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2019 June 

POSE_2019.06.01<- fread("POSE.pH.2019.06.01.csv")
POSE_2019.06.01<- POSE_2019.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.06.01<- POSE_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2019.06.02<- fread("POSE.pH.2019.06.02.csv")
POSE_2019.06.02<- POSE_2019.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude,Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.06.02<- POSE_2019.06.02 %>% 
 group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# POSE - 2019 September 

POSE_2019.09.01<- fread("POSE.pH.2019.09.01.csv")
POSE_2019.09.01<- POSE_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89440, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14729, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.09.01<- POSE_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE_2019.09.02<- fread("POSE.pH.2019.09.02.csv")
POSE_2019.09.02<- POSE_2019.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'POSE', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.89519, .before= 'startDateTime') %>%
   add_column(Longitude= -78.14786, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

POSE_2019.09.02<- POSE_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

POSE<- bind_rows(POSE_2017.09.02, POSE_2018.03.01, POSE_2018.03.02, POSE_2018.06.01, POSE_2018.06.02, POSE_2018.09.01, POSE_2018.09.02, POSE_2019.03.01, POSE_2019.03.02, POSE_2019.06.01, POSE_2019.06.02, POSE_2019.09.01, POSE_2019.09.02)
POSE
```


# 2)KING
```{r}
# KING - 2017 September 
KING_2017.09.01<- fread("KING.pH.2017.09.01.csv")
KING_2017.09.01<- KING_2017.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2017.09.01<- KING_2017.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2017.09.02<- fread("KING.pH.2017.09.02.csv")
KING_2017.09.02<- KING_2017.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2017.09.02<- KING_2017.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))


# KING - 2018 March 

KING_2018.03.01<- fread("KING.pH.2018.03.01.csv")
KING_2018.03.01<- KING_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.03.01<- KING_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2018.03.02<- fread("KING.pH.2018.03.02.csv")
KING_2018.03.02<- KING_2018.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.03.02<- KING_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# KING - 2018 June

KING_2018.06.01<- fread("KING.pH.2018.06.01.csv")
KING_2018.06.01<- KING_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.06.01<- KING_2018.06.01 %>% 
 group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2018.06.02<- fread("KING.pH.2018.06.02.csv")
KING_2018.06.02<- KING_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.06.02<- KING_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# KING - 2018 September

KING_2018.09.01<- fread("KING.pH.2018.09.01.csv")
KING_2018.09.01<- KING_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.09.01<- KING_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2018.09.02<- fread("KING.pH.2018.09.02.csv")
KING_2018.09.02<- KING_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2018.09.02<- KING_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# KING - 2019 April 

KING_2019.04.01<- fread("KING.pH.2019.04.01.csv")
KING_2019.04.01<- KING_2019.04.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.04.01<- KING_2019.04.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2019.04.02<- fread("KING.pH.2019.04.02.csv")
KING_2019.04.02<- KING_2019.04.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.04.02<- KING_2019.04.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# KING - 2019 June 

KING_2019.06.01<- fread("KING.pH.2019.06.01.csv")
KING_2019.06.01<- KING_2019.06.01 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.06.01<- KING_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2019.06.02<- fread("KING.pH.2019.06.02.csv")
KING_2019.06.02<- KING_2019.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.06.02<- KING_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# KING - 2019 October 

KING_2019.10.01<- fread("KING.pH.2019.10.01.csv")
KING_2019.10.01<- KING_2019.10.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
   add_column(Latitude= 39.104761, .before= 'startDateTime') %>%
   add_column(Longitude= -96.602339, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-10.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.10.01<- KING_2019.10.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING_2019.10.02<- fread("KING.pH.2019.10.02.csv")
KING_2019.10.02<- KING_2019.10.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'KING', .before= 'startDateTime') %>% 
    add_column(Latitude= 39.105069, .before= 'startDateTime') %>%
   add_column(Longitude= -96.603387, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-10.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

KING_2019.10.02<- KING_2019.10.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

KING<- bind_rows(KING_2017.09.01, KING_2017.09.02, KING_2018.03.01, KING_2018.03.02, KING_2018.06.01, KING_2018.06.02, KING_2018.09.01, KING_2018.09.02, KING_2019.04.01, KING_2019.04.02, KING_2019.06.01, KING_2019.06.02, KING_2019.10.01, KING_2019.10.02) 
KING
```


# 3)MCDI
```{r}
# MCDI - 2018 March 

MCDI_2018.03.01<- fread("MCDI.pH.2018.03.01.csv")
MCDI_2018.03.01<- MCDI_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2018.03.01<- MCDI_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI_2018.03.02<- fread("MCDI.pH.2018.03.02.csv")
MCDI_2018.03.02<- MCDI_2018.03.02 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.946553, .before= 'startDateTime') %>%
   add_column(Longitude= -96.442948, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2018.03.02<- MCDI_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MCDI - 2018 June

MCDI_2018.06.01<- fread("MCDI.pH.2018.06.01.csv")
MCDI_2018.06.01<- MCDI_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2018.06.01<- MCDI_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI_2018.06.02<- fread("MCDI.pH.2018.06.02.csv")
MCDI_2018.06.02<- MCDI_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>%
   add_column(Latitude= 38.946553, .before= 'startDateTime') %>%
   add_column(Longitude= -96.442948, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2018.06.02<- MCDI_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MCDI - 2018 October

MCDI_2018.10.01<- fread("MCDI.pH.2018.10.csv")
MCDI_2018.10.01<- MCDI_2018.10.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-10", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2018.10.01<- MCDI_2018.10.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MCDI - 2019 March 

MCDI_2019.03.01<- fread("MCDI.pH.2019.03.01.csv")
MCDI_2019.03.01<- MCDI_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2019.03.01<- MCDI_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI_2019.03.02<- fread("MCDI.pH.2019.03.02.csv")
MCDI_2019.03.02<- MCDI_2019.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.946553, .before= 'startDateTime') %>%
   add_column(Longitude= -96.442948, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2019.03.02<- MCDI_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MCDI - 2019 August 

MCDI_2019.08.01<- fread("MCDI.pH.2019.08.01.csv")
MCDI_2019.08.01<- MCDI_2019.08.01 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-08.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2019.08.01<- MCDI_2019.08.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI_2019.08.02<- fread("MCDI.pH.2019.08.02.csv")
MCDI_2019.08.02<- MCDI_2019.08.02 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.946553, .before= 'startDateTime') %>%
   add_column(Longitude= -96.442948, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-08.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2019.08.02<- MCDI_2019.08.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MCDI - 2019 September 

MCDI_2019.09.01<- fread("MCDI.pH.2019.09.01.csv")
MCDI_2019.09.01<- MCDI_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.947228, .before= 'startDateTime') %>%
   add_column(Longitude= -96.443842, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH,specificConductance) 

MCDI_2019.09.01<- MCDI_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI_2019.09.02<- fread("MCDI.pH.2019.09.02.csv")
MCDI_2019.09.02<- MCDI_2019.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MCDI', .before= 'startDateTime') %>% 
   add_column(Latitude= 38.946553, .before= 'startDateTime') %>%
   add_column(Longitude= -96.442948, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MCDI_2019.09.02<- MCDI_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MCDI <- bind_rows(MCDI_2018.03.01, MCDI_2018.03.02, MCDI_2018.06.01, MCDI_2018.06.02, MCDI_2018.10.01, MCDI_2019.03.01, MCDI_2019.03.02, MCDI_2019.08.01, MCDI_2019.08.02, MCDI_2019.09.01, MCDI_2019.09.02 )
MCDI
```


# 4)LECO

```{r}
# LECO - 2017 May 
LECO_2017.05.01<- fread("LECO.pH.2017.05.01.csv")
LECO_2017.05.01<- LECO_2017.05.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-05.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2017.05.01<- LECO_2017.05.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

LECO_2017.05.02<- fread("LECO.pH.2017.05.02.csv")
LECO_2017.05.02<- LECO_2017.05.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.692201, .before= 'startDateTime') %>%
   add_column(Longitude= -83.504427, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-05.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2017.05.02<- LECO_2017.05.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# LECO - 2018 March 

LECO_2018.03.01<- fread("LECO.pH.2018.03.01.csv")
LECO_2018.03.01<- LECO_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2018.03.01<- LECO_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

LECO_2018.03.02<- fread("LECO.pH.2018.03.02.csv")
LECO_2018.03.02<- LECO_2018.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>%
   add_column(Latitude= 35.692201, .before= 'startDateTime') %>%
   add_column(Longitude= -83.504427, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2018.03.02<- LECO_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# LECO - 2018 June

LECO_2018.06.01<- fread("LECO.pH.2018.06.01.csv")
LECO_2018.06.01<- LECO_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2018.06.01<- LECO_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

LECO_2018.06.02<- fread("LECO.pH.2018.06.02.csv")
LECO_2018.06.02<- LECO_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.692201, .before= 'startDateTime') %>%
   add_column(Longitude= -83.504427, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2018.06.02<- LECO_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# LECO - 2019 March 

LECO_2019.03.01<- fread("LECO.pH.2019.03.csv")
LECO_2019.03.01<- LECO_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2019.03.01<- LECO_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# LECO - 2019 June 

LECO_2019.06.01<- fread("LECO.pH.2019.06.csv")
LECO_2019.06.01<- LECO_2019.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2019.06.01<- LECO_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# LECO - 2019 September 

LECO_2019.09.01<- fread("LECO.pH.2019.09.csv")
LECO_2019.09.01<- LECO_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'LECO', .before= 'startDateTime') %>% 
   add_column(Latitude= 35.689128, .before= 'startDateTime') %>%
   add_column(Longitude= -83.503356, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

LECO_2019.09.01<- LECO_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))


LECO <- bind_rows(LECO_2017.05.01, LECO_2017.05.02, LECO_2018.03.01, LECO_2018.03.02, LECO_2018.06.01, LECO_2018.06.02, LECO_2019.03.01, LECO_2019.06.01, LECO_2019.09.01)
LECO
```


# 5)MAYF 
```{r}
# MAYF - 2017 March 
MAYF_2017.03.01<- fread("MAYF.pH.2017.03.01.csv")
MAYF_2017.03.01<- MAYF_2017.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2017.03.01<- MAYF_2017.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2017.03.02<- fread("MAYF.pH.2017.03.02.csv")
MAYF_2017.03.02<- MAYF_2017.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2017.03.02<- MAYF_2017.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2017 September 
MAYF_2017.09.01<- fread("MAYF.pH.2017.09.01.csv")
MAYF_2017.09.01<- MAYF_2017.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2017.09.01<- MAYF_2017.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2017.09.02<- fread("MAYF.pH.2017.09.02.csv")
MAYF_2017.09.02<- MAYF_2017.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2017.09.02<- MAYF_2017.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2018 March 

MAYF_2018.03.01<- fread("MAYF.pH.2018.03.01.csv")
MAYF_2018.03.01<- MAYF_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.03.01<- MAYF_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2018.03.02<- fread("MAYF.pH.2018.03.02.csv")
MAYF_2018.03.02<- MAYF_2018.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.03.02<- MAYF_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2018 June

MAYF_2018.06.01<- fread("MAYF.pH.2018.06.01.csv")
MAYF_2018.06.01<- MAYF_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.06.01<- MAYF_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2018.06.02<- fread("MAYF.pH.2018.06.02.csv")
MAYF_2018.06.02<- MAYF_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.06.02<- MAYF_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2018 September

MAYF_2018.09.01<- fread("MAYF.pH.2018.09.01.csv")
MAYF_2018.09.01<- MAYF_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.09.01<- MAYF_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2018.09.02<- fread("MAYF.pH.2018.09.02.csv")
MAYF_2018.09.02<- MAYF_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2018.09.02<- MAYF_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2019 March 

MAYF_2019.03.01<- fread("MAYF.pH.2019.03.01.csv")
MAYF_2019.03.01<- MAYF_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.03.01<- MAYF_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2019.03.02<- fread("MAYF.pH.2019.03.02.csv")
MAYF_2019.03.02<- MAYF_2019.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.03.02<- MAYF_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2019 June 

MAYF_2019.06.01<- fread("MAYF.pH.2019.06.01.csv")
MAYF_2019.06.01<- MAYF_2019.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>%
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.06.01<- MAYF_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2019.06.02<- fread("MAYF.pH.2019.06.02.csv")
MAYF_2019.06.02<- MAYF_2019.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.06.02<- MAYF_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# MAYF - 2019 September 

MAYF_2019.09.01<- fread("MAYF.pH.2019.09.01.csv")
MAYF_2019.09.01<- MAYF_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'MAYF', .before= 'startDateTime') %>% 
   add_column(Latitude= 32.960401, .before= 'startDateTime') %>%
   add_column(Longitude= -87.407848, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.09.01<- MAYF_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF_2019.09.02<- fread("MAYF.pH.2019.09.02.csv")
MAYF_2019.09.02<- MAYF_2019.09.02 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'MAYF', .before= 'startDateTime') %>%
   add_column(Latitude= 32.961588, .before= 'startDateTime') %>%
   add_column(Longitude= -87.408214, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

MAYF_2019.09.02<- MAYF_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

MAYF<- bind_rows(MAYF_2017.03.01, MAYF_2017.03.02, MAYF_2017.09.01, MAYF_2017.09.02, MAYF_2018.03.01, MAYF_2018.03.02, MAYF_2018.06.01, MAYF_2018.06.02, MAYF_2018.09.01, MAYF_2018.09.02, MAYF_2019.03.01, MAYF_2019.03.02, MAYF_2019.06.01, MAYF_2019.06.02, MAYF_2019.09.01, MAYF_2019.09.02)
MAYF
```

# 6)PRIN 

```{r}
# PRIN - 2017 September 
PRIN_2017.09.01<- fread("PRIN.pH.2017.09.01.csv")
PRIN_2017.09.01<- PRIN_2017.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2017.09.01<- PRIN_2017.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2017.09.02<- fread("PRIN.pH.2017.09.02.csv")
PRIN_2017.09.02<- PRIN_2017.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2017.09.02<- PRIN_2017.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2018 March 

PRIN_2018.03.01<- fread("PRIN.pH.2018.03.01.csv")
PRIN_2018.03.01<- PRIN_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>%
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.03.01<- PRIN_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2018.03.02<- fread("PRIN.pH.2018.03.02.csv")
PRIN_2018.03.02<- PRIN_2018.03.02 %>% 
  filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.03.02<- PRIN_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2018 June

PRIN_2018.06.01<- fread("PRIN.pH.2018.06.01.csv")
PRIN_2018.06.01<- PRIN_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.06.01<- PRIN_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2018.06.02<- fread("PRIN.pH.2018.06.02.csv")
PRIN_2018.06.02<- PRIN_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.06.02<- PRIN_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2018 September

PRIN_2018.09.01<- fread("PRIN.pH.2018.09.01.csv")
PRIN_2018.09.01<- PRIN_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.09.01<- PRIN_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2018.09.02<- fread("PRIN.pH.2018.09.02.csv")
PRIN_2018.09.02<- PRIN_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2018.09.02<- PRIN_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2019 March 

PRIN_2019.03.01<- fread("PRIN.pH.2019.03.01.csv")
PRIN_2019.03.01<- PRIN_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.03.01<- PRIN_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2019.03.02<- fread("PRIN.pH.2019.03.02.csv")
PRIN_2019.03.02<- PRIN_2019.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.03.02<- PRIN_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2019 June 

PRIN_2019.06.01<- fread("PRIN.pH.2019.06.01.csv")
PRIN_2019.06.01<- PRIN_2019.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.06.01<- PRIN_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2019.06.02<- fread("PRIN.pH.2019.06.02.csv")
PRIN_2019.06.02<- PRIN_2019.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.06.02<- PRIN_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2019 September 

PRIN_2019.09.01<- fread("PRIN.pH.2019.09.01.csv")
PRIN_2019.09.01<- PRIN_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378354, .before= 'startDateTime') %>%
   add_column(Longitude= -97.783597, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.09.01<- PRIN_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN_2019.09.02<- fread("PRIN.pH.2019.09.02.csv")
PRIN_2019.09.02<- PRIN_2019.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'PRIN', .before= 'startDateTime') %>% 
   add_column(Latitude= 33.378426, .before= 'startDateTime') %>%
   add_column(Longitude= -97.781495, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

PRIN_2019.09.02<- PRIN_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

PRIN<- bind_rows(PRIN_2017.09.01, PRIN_2017.09.02, PRIN_2018.03.01, PRIN_2018.03.02, PRIN_2018.06.01, PRIN_2018.06.02, PRIN_2018.09.01, PRIN_2018.09.02, PRIN_2019.03.01, PRIN_2019.03.02, PRIN_2019.06.01, PRIN_2019.06.02, PRIN_2019.09.01, PRIN_2019.09.02)
PRIN
```


# 7) BLDE 

```{r}
# BLDE - 2018 September

BLDE_2018.09.01<- fread("BLDE.pH.2018.09.01.csv")
BLDE_2018.09.01<- BLDE_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.951119, .before= 'startDateTime') %>%
   add_column(Longitude= -110.58817, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2018.09.01<- BLDE_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

BLDE_2018.09.02<- fread("BLDE.pH.2018.09.02.csv")
BLDE_2018.09.02<- BLDE_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.953606, .before= 'startDateTime') %>%
   add_column(Longitude= -110.589395, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2018.09.02<- BLDE_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# PRIN - 2019 April 

BLDE_2019.04.01<- fread("BLDE.pH.2019.04.01.csv")
BLDE_2019.04.01<- BLDE_2019.04.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.951119, .before= 'startDateTime') %>%
   add_column(Longitude= -110.58817, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.04.01<- BLDE_2019.04.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

BLDE_2019.04.02<- fread("BLDE.pH.2019.04.02.csv")
BLDE_2019.04.02<- BLDE_2019.04.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.953606, .before= 'startDateTime') %>%
   add_column(Longitude= -110.589395, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.04.02<- BLDE_2019.04.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# BLDE - 2019 August 

BLDE_2019.08.01<- fread("BLDE.pH.2019.08.01.csv")
BLDE_2019.08.01<- BLDE_2019.08.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.951119, .before= 'startDateTime') %>%
   add_column(Longitude= -110.58817, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-08.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.08.01<- BLDE_2019.08.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

BLDE_2019.08.02<- fread("BLDE.pH.2019.08.02.csv")
BLDE_2019.08.02<- BLDE_2019.08.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.953606, .before= 'startDateTime') %>%
   add_column(Longitude= -110.589395, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-08.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.08.02<- BLDE_2019.08.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# BLDE - 2019 September 

BLDE_2019.09.01<- fread("BLDE.pH.2019.09.01.csv")
BLDE_2019.09.01<- BLDE_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.951119, .before= 'startDateTime') %>%
   add_column(Longitude= -110.58817, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.09.01<- BLDE_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

BLDE_2019.09.02<- fread("BLDE.pH.2019.09.02.csv")
BLDE_2019.09.02<- BLDE_2019.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'BLDE', .before= 'startDateTime') %>% 
   add_column(Latitude= 44.953606, .before= 'startDateTime') %>%
   add_column(Longitude= -110.589395, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

BLDE_2019.09.02<- BLDE_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

BLDE<- bind_rows(BLDE_2018.09.01, BLDE_2018.09.02, BLDE_2019.04.01, BLDE_2019.04.02, BLDE_2019.08.01, BLDE_2019.08.02, BLDE_2019.09.01, BLDE_2019.09.02) 
BLDE

```


# 8) COMO
```{r}
# COMO - 2017 September 
COMO_2017.09.01<- fread("COMO.pH.2017.09.01.csv")
COMO_2017.09.01<- COMO_2017.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
   add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2017.09.01<- COMO_2017.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2017.09.02<- fread("COMO.pH.2017.09.02.csv")
COMO_2017.09.02<- COMO_2017.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
   add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2017-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2017.09.02<- COMO_2017.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2018 March 

COMO_2018.03.01<- fread("COMO.pH.2018.03.01.csv")
COMO_2018.03.01<- COMO_2018.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.03.01<- COMO_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2018.03.02<- fread("COMO.pH.2018.03.02.csv")
COMO_2018.03.02<- COMO_2018.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.03.02<- COMO_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2018 June

COMO_2018.06.01<- fread("COMO.pH.2018.06.01.csv")
COMO_2018.06.01<- COMO_2018.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.06.01<- COMO_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2018.06.02<- fread("COMO.pH.2018.06.02.csv")
COMO_2018.06.02<- COMO_2018.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.06.02<- COMO_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2018 September

COMO_2018.09.01<- fread("COMO.pH.2018.09.01.csv")
COMO_2018.09.01<- COMO_2018.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.09.01<- COMO_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2018.09.02<- fread("COMO.pH.2018.09.02.csv")
COMO_2018.09.02<- COMO_2018.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2018.09.02<- COMO_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2019 March 

COMO_2019.03.01<- fread("COMO.pH.2019.03.01.csv")
COMO_2019.03.01<- COMO_2019.03.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>%
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.03.01<- COMO_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2019.03.02<- fread("COMO.pH.2019.03.02.csv")
COMO_2019.03.02<- COMO_2019.03.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.03.02<- COMO_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2019 June 

COMO_2019.06.01<- fread("COMO.pH.2019.06.01.csv")
COMO_2019.06.01<- COMO_2019.06.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.06.01<- COMO_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
 summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2019.06.02<- fread("COMO.pH.2019.06.02.csv")
COMO_2019.06.02<- COMO_2019.06.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>% 
   add_column(Location= 'COMO', .before= 'startDateTime') %>%
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>%
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.06.02<- COMO_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

# COMO - 2019 September 

COMO_2019.09.01<- fread("COMO.pH.2019.09.01.csv")
COMO_2019.09.01<- COMO_2019.09.01 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.03495, .before= 'startDateTime') %>%
   add_column(Longitude= -105.545311, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.09.01<- COMO_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO_2019.09.02<- fread("COMO.pH.2019.09.02.csv")
COMO_2019.09.02<- COMO_2019.09.02 %>% 
   filter(!is.na(pH) &!is.na(specificConductance)) %>%  
   add_column(Location= 'COMO', .before= 'startDateTime') %>% 
    add_column(Latitude= 40.034953, .before= 'startDateTime') %>%
   add_column(Longitude= -105.544407, .before= 'startDateTime') %>%
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance) 

COMO_2019.09.02<- COMO_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), specificConductance= mean(specificConductance))

COMO<- bind_rows(COMO_2017.09.01, COMO_2017.09.02, COMO_2018.03.01, COMO_2018.03.02, COMO_2018.06.01, COMO_2018.06.02, COMO_2018.09.01, COMO_2018.09.02, COMO_2019.03.01, COMO_2019.03.02, COMO_2019.06.01, COMO_2019.06.02, COMO_2019.09.01, COMO_2019.09.02)
COMO
```

# 1651 lines of code later... 

```{r}
pH.POSE.to.COMO<- bind_rows(POSE, KING, MCDI, LECO, MAYF, PRIN, BLDE, COMO)
pH.POSE.to.COMO

write.csv(pH.POSE.to.COMO, "pH.POSE.to.COMO.csv")
```

```{r}
##wlou, syca, redb, mart, mcra, bigc, tecr, cari 
#invertebrates collected in spring, summer, fall
getwd()
setwd("/Users/sarahravoth/Desktop")
require(data.table)
```

#WLOU
``` {r}
#no 2017 data

#wlou 2018 april 
wlou_2018.04.01 <- fread("WLOU.pH.2018.04.01.csv")
wlou_2018.04.01 <- wlou_2018.04.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-04.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.891253", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.914483", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.04.01<- wlou_2018.04.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
wlou_2018.04.01 

###
wlou_2018.04.02 <- fread("WLOU.pH.2018.04.02.csv")
wlou_2018.04.02 <- wlou_2018.04.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-04.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.890669", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.911314", .before= 'startDateTime') %>% 
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.04.02<- wlou_2018.04.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#wlou 2018 june 
wlou_2018.06.01 <- fread("WLOU.pH.2018.06.01.csv")
wlou_2018.06.01 <- wlou_2018.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.891253", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.914483", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.06.01<- wlou_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
wlou_2018.06.02 <- fread("WLOU.pH.2018.06.02.csv")
wlou_2018.06.02 <- wlou_2018.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.890669", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.911314", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.06.02<- wlou_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
             conductance=mean(specificConductance))

#wlou 2018 october
wlou_2018.10.01 <- fread("WLOU.pH.2018.10.01.csv")
wlou_2018.10.01 <- wlou_2018.10.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-10.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.891253", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.914483", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.10.01<- wlou_2018.10.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
             conductance=mean(specificConductance))
wlou_2018.10.01
###
wlou_2018.10.02 <- fread("WLOU.pH.2018.10.02.csv")
wlou_2018.10.02 <- wlou_2018.10.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="WLOU", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-10.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "39.890669", .before= 'startDateTime') %>% 
  add_column(Longitude = "-105.911314", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

wlou_2018.10.02<- wlou_2018.10.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#no 2019 data
```


#SYCA 
```{r}
#no 2017 data
#no 2018 data

#syca 2019 march
syca_2019.03.01 <- fread("SYCA.pH.2019.03.01.csv")
syca_2019.03.01 <- syca_2019.03.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.751702", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.508604", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.03.01<- syca_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
syca_2019.03.02 <- fread("SYCA.pH.2019.03.02.csv")
syca_2019.03.02 <- syca_2019.03.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.75088", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.50813", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.03.02<- syca_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#syca 2019 june
syca_2019.06.01 <- fread("SYCA.pH.2019.06.01.csv")
syca_2019.06.01 <- syca_2019.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.751702", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.508604", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.06.01<- syca_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
syca_2019.06.02 <- fread("SYCA.pH.2019.06.02.csv")
syca_2019.06.02 <- syca_2019.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.75088", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.50813", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.06.02<- syca_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#syca 2019 september
syca_2019.09.01 <- fread("SYCA.pH.2019.09.01.csv")
syca_2019.09.01 <- syca_2019.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.751702", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.508604", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.09.01<- syca_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
syca_2019.09.02 <- fread("SYCA.pH.2019.09.02.csv")
syca_2019.09.02 <- syca_2019.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="SYCA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "33.75088", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.50813", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

syca_2019.09.02<- syca_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
```

#REDB
```{r}
#no 2017 data

#redb 2018 july
redb_2018.07.01 <- fread("REDB.pH.2018.07.01.csv")
redb_2018.07.01 <- redb_2018.07.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-07.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "40.78467", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79566", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2018.07.01<- redb_2018.07.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
redb_2018.07.02 <- fread("REDB.pH.2018.07.02.csv")
redb_2018.07.02 <- redb_2018.07.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-07.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "40.78366", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79811", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2018.07.02<- redb_2018.07.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))


#redb 2018 september
redb_2018.09.01 <- fread("REDB.pH.2018.09.01.csv")
redb_2018.09.01 <- redb_2018.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "40.78467", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79566", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2018.09.01<- redb_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
redb_2018.09.02 <- fread("REDB.pH.2018.09.02.csv")
redb_2018.09.02 <- redb_2018.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "40.78366", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79811", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2018.09.02<- redb_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#redb 2019 april
redb_2019.04.01 <- fread("REDB.pH.2019.04.01.csv")
redb_2019.04.01 <- redb_2019.04.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
    add_column(Latitude = "40.78467", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79566", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.04.01<- redb_2019.04.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
redb_2019.04.02 <- fread("REDB.pH.2019.04.02.csv")
redb_2019.04.02 <- redb_2019.04.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-04.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "40.78366", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79811", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.04.02<- redb_2019.04.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#redb 2019 june
redb_2019.06.01 <- fread("REDB.pH.2019.06.01.csv")
redb_2019.06.01 <- redb_2019.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
    add_column(Latitude = "40.78467", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79566", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.06.01<- redb_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
redb_2019.06.02 <- fread("REDB.pH.2019.06.02.csv")
redb_2019.06.02 <- redb_2019.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
    add_column(Latitude = "40.78366", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79811", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.06.02<- redb_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#redb 2019 september
redb_2019.09.01 <- fread("REDB.pH.2019.09.01.csv")
redb_2019.09.01 <- redb_2019.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "40.78467", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79566", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.09.01<- redb_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
redb_2019.09.02 <- fread("REDB.pH.2019.09.02.csv")
redb_2019.09.02 <- redb_2019.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="REDB", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "40.78366", .before= 'startDateTime') %>% 
  add_column(Longitude = "-111.79811", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

redb_2019.09.02<- redb_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

```

#MART 
```{r}
#no 2017 data 

#mart 2018 march 
mart_2018.03 <- fread("MART.pH.2018.03.csv")
mart_2018.03 <- mart_2018.03 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
   add_column(Latitude = "45.790826", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.93353", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2018.03<- mart_2018.03 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mart 2018 june 
mart_2018.06.01 <- fread("MART.pH.2018.06.01.csv")
mart_2018.06.01 <- mart_2018.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
   add_column(Latitude = "45.790826", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.93353", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2018.06.01<- mart_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mart_2018.06.02 <- fread("MART.pH.2018.06.02.csv")
mart_2018.06.02 <- mart_2018.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
    add_column(Latitude = "45.79233", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.929416", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2018.06.02<- mart_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mart 2018 september 
mart_2018.09 <- fread("MART.pH.2018.09.csv")
mart_2018.09 <- mart_2018.09 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
   add_column(Latitude = "45.790826", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.93353", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2018.09<- mart_2018.09 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mart 2019 march
mart_2019.03.01 <- fread("MART.pH.2019.03.01.csv")
mart_2019.03.01 <- mart_2019.03.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
   add_column(Latitude = "45.79082", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.934", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.03.01<- mart_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mart_2019.03.02 <- fread("MART.pH.2019.03.02.csv")
mart_2019.03.02 <- mart_2019.03.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "45.79232", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.929", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.03.02<- mart_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mart 2019 june
mart_2019.06.01 <- fread("MART.pH.2019.06.01.csv")
mart_2019.06.01 <- mart_2019.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "45.790826", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.93353", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.06.01<- mart_2019.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mart_2019.06.02 <- fread("MART.pH.2019.06.02.csv")
mart_2019.06.02 <- mart_2019.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "45.79233", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.929416", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.06.02<- mart_2019.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mart 2019 september
mart_2019.09.01 <- fread("MART.pH.2019.09.01.csv")
mart_2019.09.01 <- mart_2019.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "45.790826", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.93353", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.09.01<- mart_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mart_2019.09.02 <- fread("MART.pH.2019.09.02.csv")
mart_2019.09.02 <- mart_2019.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MART", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "45.79233", .before= 'startDateTime') %>% 
  add_column(Longitude = "-121.929416", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mart_2019.09.02<- mart_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
```

#MCRA 
```{r}
#mcra 2018 march
mcra_2018.03.01 <- fread("MCRA.pH.2018.03.01.csv")
mcra_2018.03.01 <- mcra_2018.03.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
     add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.03.01<- mcra_2018.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mcra_2018.03.02 <- fread("MCRA.pH.2018.03.02.csv")
mcra_2018.03.02 <- mcra_2018.03.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
     add_column(Latitude = "44.258957", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.165861", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.03.02<- mcra_2018.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mcra 2018 june
mcra_2018.06.01 <- fread("MCRA.pH.2018.06.01.csv")
mcra_2018.06.01 <- mcra_2018.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
       add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.06.01<- mcra_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mcra_2018.06.02 <- fread("MCRA.pH.2018.06.02.csv")
mcra_2018.06.02 <- mcra_2018.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
       add_column(Latitude = "44.258957", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.165861", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.06.02<- mcra_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mcra 2018 september
mcra_2018.09.01 <- fread("MCRA.pH.2018.09.01.csv")
mcra_2018.09.01 <- mcra_2018.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>%     
  add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.09.01<- mcra_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mcra_2018.09.02 <- fread("MCRA.pH.2018.09.02.csv")
mcra_2018.09.02 <- mcra_2018.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "44.258957", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.165861", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2018.09.02<- mcra_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mcra 2019 march 
mcra_2019.03.01 <- fread("MCRA.pH.2019.03.01.csv")
mcra_2019.03.01 <- mcra_2019.03.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.01", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2019.03.01<- mcra_2019.03.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mcra_2019.03.02 <- fread("MCRA.pH.2019.03.02.csv")
mcra_2019.03.02 <- mcra_2019.03.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-03.02", .before= 'startDateTime') %>% 
   add_column(Season= "Spring", .before= 'startDateTime') %>% 
  add_column(Latitude = "44.258957", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.165861", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2019.03.02<- mcra_2019.03.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mcra 2019 june
mcra_2019.06 <- fread("MCRA.pH.2019.06.csv")
mcra_2019.06 <- mcra_2019.06 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-06", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2019.06<- mcra_2019.06 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#mcra 2019 september 
mcra_2019.09.01 <- fread("MCRA.pH.2019.09.01.csv")
mcra_2019.09.01 <- mcra_2019.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "44.260355", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.164627", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2019.09.01<- mcra_2019.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
mcra_2019.09.02 <- fread("MCRA.pH.2019.09.02.csv")
mcra_2019.09.02 <- mcra_2019.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="MCRA", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "44.258957", .before= 'startDateTime') %>% 
  add_column(Longitude = "-122.165861", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

mcra_2019.09.02<- mcra_2019.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
```

#BIGC 
```{r}
#no 2017 data 

#bigc 2018 june
bigc_2018.06.01 <- fread("BIGC.pH.2018.06.01.csv")
bigc_2018.06.01 <- bigc_2018.06.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="BIGC", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "37.058708", .before= 'startDateTime') %>% 
  add_column(Longitude = "-119.256499", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

bigc_2018.06.01<- bigc_2018.06.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
bigc_2018.06.02 <- fread("BIGC.pH.2018.06.02.csv")
bigc_2018.06.02 <- bigc_2018.06.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="BIGC", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-06.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "37.057672", .before= 'startDateTime') %>% 
  add_column(Longitude = "-119.255375", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

bigc_2018.06.02<- bigc_2018.06.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#bigc 2018 september 
bigc_2018.09.01 <- fread("BIGC.pH.2018.09.01.csv")
bigc_2018.09.01 <- bigc_2018.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="BIGC", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "37.058702", .before= 'startDateTime') %>% 
  add_column(Longitude = "-119.2565", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

bigc_2018.09.01<- bigc_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
bigc_2018.09.02 <- fread("BIGC.pH.2018.09.02.csv")
bigc_2018.09.02 <- bigc_2018.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="BIGC", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
  add_column(Latitude = "37.057667", .before= 'startDateTime') %>% 
  add_column(Longitude = "-119.255374", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

bigc_2018.09.02<- bigc_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#no 2019 data 
```

#TECR
```{r}
#no tecr data for 2017, 2018, 2019
```

#OKSR
```{r}
#no oksr data for 2017, 2018, 2019
```

#CARI
```{r}
#cari 2018 july 
cari_2018.07.01 <- fread("CARI.pH.2018.07.01.csv")
cari_2018.07.01 <- cari_2018.07.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-07.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "65.152537", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.507852", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2018.07.01<- cari_2018.07.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
cari_2018.07.02 <- fread("CARI.pH.2018.07.02.csv")
cari_2018.07.02 <- cari_2018.07.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-07.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "65.153073", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.501999", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2018.07.02<- cari_2018.07.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#cari 2018 september 
cari_2018.09.01 <- fread("CARI.pH.2018.09.01.csv")
cari_2018.09.01 <- cari_2018.09.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.01", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "65.152537", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.507852", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2018.09.01<- cari_2018.09.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
cari_2018.09.02 <- fread("CARI.pH.2018.09.02.csv")
cari_2018.09.02 <- cari_2018.09.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2018-09.02", .before= 'startDateTime') %>% 
   add_column(Season= "Fall", .before= 'startDateTime') %>% 
    add_column(Latitude = "65.153073", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.501999", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2018.09.02<- cari_2018.09.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))

#cari 2019 july 
cari_2019.07.01 <- fread("CARI.pH.2019.07.01.csv")
cari_2019.07.01 <- cari_2019.07.01 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-07.01", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "65.152537", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.507852", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2019.07.01<- cari_2019.07.01 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
###
cari_2019.07.02 <- fread("CARI.pH.2019.07.02.csv")
cari_2019.07.02 <- cari_2019.07.02 %>% 
  filter(!is.na(pH), !is.na(specificConductance)) %>% 
  add_column(Location="CARI", .before="startDateTime") %>% 
   add_column(CollectionMethod= "YSI.EXO", .before='startDateTime') %>% 
   add_column(Date= "2019-07.02", .before= 'startDateTime') %>% 
   add_column(Season= "Summer", .before= 'startDateTime') %>% 
  add_column(Latitude = "65.153073", .before= 'startDateTime') %>% 
  add_column(Longitude = "-147.501999", .before= 'startDateTime') %>%
  dplyr::select(Location, Date, Season, CollectionMethod, pH, specificConductance, Longitude, Latitude) 

cari_2019.07.02<- cari_2019.07.02 %>% 
  group_by(Location, Date, Latitude, Longitude, Season, CollectionMethod) %>% 
  summarise(pH= mean(pH), 
            conductance=mean(specificConductance))
```


#joining everything together 
```{r}
pH_wlou_to_cari <- bind_rows(wlou_2018.04.01, wlou_2018.04.02, wlou_2018.06.01,wlou_2018.06.02,wlou_2018.10.01,wlou_2018.10.02, 
          syca_2019.03.01, syca_2019.03.02,syca_2019.06.01,syca_2019.06.02,syca_2019.09.01,syca_2019.09.02, 
redb_2018.07.01,redb_2018.07.02,redb_2018.09.01,redb_2018.09.02,redb_2019.04.01,redb_2019.04.02,redb_2019.06.01,redb_2019.06.02,redb_2019.09.01,redb_2019.09.02, 
mart_2018.03, mart_2018.06.01, mart_2018.06.02, mart_2018.09, mart_2019.03.01,mart_2019.03.02,mart_2019.06.01 ,mart_2019.06.02,mart_2019.09.01,mart_2019.09.02, 
mcra_2018.03.01,mcra_2018.03.02,mcra_2018.06.01,mcra_2018.06.02,mcra_2018.09.01,mcra_2018.09.02,mcra_2019.03.01,mcra_2019.03.02,mcra_2019.06,mcra_2019.09.01,mcra_2019.09.02,
bigc_2018.06.01,bigc_2018.06.02,bigc_2018.09.01,bigc_2018.09.02, cari_2018.07.01,cari_2018.07.02,cari_2018.09.01,cari_2018.09.02,cari_2019.07.01,cari_2019.07.02)

write.csv(pH_wlou_to_cari, "pH_wlou_to_cari.csv") 

```

# Putting all sites together 
```{r}
pH_wlou_to_cari<- read_csv("pH_wlou_to_cari.csv")
pH_wlou_to_cari<- pH_wlou_to_cari %>% 
  rename("specificConductance"= conductance)

final_pH<- bind_rows(pH.POSE.to.COMO, pH_wlou_to_cari)
final_pH <- final_pH %>% 
  dplyr::select(Location, Date, Latitude, Longitude, Season, CollectionMethod, pH, specificConductance)
write.csv(final_pH, "final_pH.csv")
```

