---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
invert_genera<- read_csv("invert_genera.csv", col_names = TRUE)

ig_allyear_14sites <- invert_genera %>%
  filter(siteID == c("POSE","KING", "MCDI", "LECO", "MAYF", "PRIN", "BLDE", 
  "COMO", "WLOU", "SYCA", "REDB", "MART", "MCRA", "BIGC", "CARI", "TECR")) %>%
  filter(collectDate >= "2017-01-01"& collectDate <= "2019-12-30") %>%
  mutate(collectDate = as.POSIXct(collectDate, "GMT"))

```


```{r}
ig_2017<-
  ig_allyear_14sites%>%
  filter(collectDate >= "2017-01-01" & collectDate <= "2017-12-30") %>%
    mutate(year = "2017")

ig_Spring_2017 <- ig_2017 %>%
  filter(collectDate >= "2017-03-01" & collectDate <= "2017-5-31") %>%
  mutate(season = "Spring")

ig_Summer_2017 <- ig_2017 %>%
  filter(collectDate >= "2017-06-01" & collectDate <= "2017-8-31") %>%
  mutate(season = "Summer")

ig_Fall_2017 <- ig_2017 %>%
  filter(collectDate >= "2017-09-01" & collectDate <= "2017-11-30") %>%
  mutate(season = "Fall")

ig_Winter_2017 <-ig_2017 %>%
  filter(collectDate >= "2017-01-01" & collectDate <= "2017-02-28") %>%
  mutate(season = "Winter")

invert_genera_2017_season <- 
  rbind(ig_Spring_2017, ig_Summer_2017, ig_Fall_2017, ig_Winter_2017)
```

```{r}
ig_2018 <- ig_allyear_14sites%>%
  filter(collectDate >= "2018-01-01" & collectDate <= "2018-12-30") %>%
  mutate(year = "2018")

ig_Spring_2018 <- ig_2018 %>%
  filter(collectDate >= "2018-03-01" & collectDate <= "2018-5-31") %>%
  mutate(season = "Spring")

ig_Summer_2018 <- ig_2018 %>%
  filter(collectDate >= "2018-06-01" & collectDate <= "2018-8-31") %>%
  mutate(season = "Summer")

ig_Fall_2018 <- ig_2018 %>%
  filter(collectDate >= "2018-09-01" & collectDate <= "2018-11-30") %>%
  mutate(season = "Fall")

ig_Winter_2018 <-ig_2018 %>%
  filter(collectDate >= "2018-01-01" & collectDate <= "2018-02-28") %>%
  mutate(season = "Winter")

invert_genera_2018_season <- 
  rbind(ig_Spring_2018, ig_Summer_2018, ig_Fall_2018, ig_Winter_2018)
```

```{r}
invert_genera_season <- rbind(invert_genera_2017_season, invert_genera_2018_season)

write.csv(invert_genera_season,
          'C:\\Users\\Eve Zhao\\Desktop\\EEB313\\group assignment\\invert_genera_season.csv', 
          row.names = FALSE)

```

